### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ZiyanZhu1994** [rdpeng/ProgrammingAssignment2#1739]

**Comment by Alfredhomere** [comment]
Hi, even if I am still waiting for my evaluation results, I hope I follow the good steps:
- Develop my code in R Studio,
- clone the repository of Github
- Copy the code entirely in the edition page after forking
- save the edited page at the bottom left (green) of the same page.
- copy the URL and paste in the coursera assignment and save the draft
- load the cachematrix.R on the Github page
- copy the string code of 40 characters that appears
- open the coursera assignment and paste where necessary
  Hope this helpful,
  Thank's
